# Generated by Django 2.0.5 on 2018-10-13 08:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('myApp1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('disc', models.TextField()),
                ('url', models.CharField(max_length=200)),
                ('picture', models.ImageField(upload_to='upload/')),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
