# Generated by Django 2.0.5 on 2018-10-13 09:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('myApp1', '0002_photos'),
    ]

    operations = [
        migrations.CreateModel(
            name='oneDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('content', models.CharField(max_length=200)),
                ('note', models.CharField(max_length=200)),
            ],
        ),
    ]
