# Generated by Django 2.0.3 on 2018-05-06 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp1', '0003_auto_20180402_1828'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
