# Generated by Django 2.0.5 on 2018-10-13 10:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('myApp1', '0003_oneday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oneday',
            old_name='date',
            new_name='title',
        ),
    ]
