# Generated by Django 2.0.5 on 2018-10-13 08:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='com',
            name='createDate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
